### ISSUE TITLE
Pre-Commit fails if no openapi generator is installed

### ISSUE THREAD

**Issue by white0ut** [dudasaus/tierlist#27]
I installed this to get it working:

```
npm install @openapitools/openapi-generator-cli -D
```

Mine failed with `Unknown option -i` but I'm guessing this would fail for other reasons in that openapi generator isn't installed.

Ideally there'd be some way to install this if it's missing

**Comment by dudasaus** [comment]
I'm migrating us to a better codegen. Still probably need to `npm i` in the root dir when there's a missing dep

**Comment by dudasaus** [comment]
Everything should be good to go - if you get a missing dependency error, `npm i` to update deps. Maybe I can put that in a pull hook or something to check for added deps!
